RED='\033[0;31m'
GREEN='\033[0;32m'
BLACK='\033[0m'
echo comment_before_rooms
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_before_rooms
echo ${BLACK}
echo comment_before_ant
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_before_ant
echo ${BLACK}
echo comment_after_end
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_after_end
echo ${BLACK}
echo comment_b_a_rooms
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_b_a_rooms
echo ${BLACK}
echo comment_pipe
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_pipe
echo ${BLACK}
echo comment_before_start
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_before_start
echo ${BLACK}
echo comment_after_start2
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_after_start2
echo ${BLACK}
echo comment_after_end2
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_after_end2
echo ${BLACK}
echo comment_after_rooms
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_after_rooms
echo ${BLACK}
echo comment_after_ant
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_after_ant
echo ${BLACK}
echo comment_room
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_room
echo ${BLACK}
echo comment_after_start
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_after_start
echo ${BLACK}
echo comment_mass_rooms
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_mass_rooms
echo ${BLACK}
echo comment_###2
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_###2
echo ${BLACK}
echo comment_###
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_###
echo ${BLACK}
echo comment_b_a_pipes
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_b_a_pipes
echo ${BLACK}
echo comment_after_pipes
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_after_pipes
echo ${BLACK}
echo comment_before_pipes
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_before_pipes
echo ${BLACK}
echo comment_mass_pipes
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_mass_pipes
echo ${BLACK}
echo comment_before_ant2
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_before_ant2
echo ${BLACK}
echo comment_before_end
echo ${GREEN}
./lem-in lemon_test/lem-in_maps/comment/comment_before_end
echo ${BLACK}
